In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("metro_countries_cities.csv")
df.head()

,city,country,name,year,year_last_expansion,stations,length_km,annual_ridership_mill,region
0,Algiers,Algeria,Algiers Metro,2011,2018,19,185,45.30,africa
1,Buenos Aires,Argentina,Buenos Aires Underground,1913,2019,90,567,74.00,latin_america
2,Yerevan,Armenia,Yerevan Metro,1981,1996,10,134,10.75,asia
3,Sydney,Australia,Sydney Metro,2019,2019,13,36,12.90,australia
4,Vienna,Austria,Vienna U-Bahn,1976,2017,98,833,459.80,europe

In [7]:
df.columns.tolist()

['city',
 'country',
 'name',
 'year',
 'year_last_expansion',
 'stations',
 'length_km',
 'annual_ridership_mill',
 'region']

In [9]:
df.shape

(198, 9)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   198 non-null    str
 1   country                198 non-null    str
 2   name                   198 non-null    str
 3   year                   198 non-null    int64
 4   year_last_expansion    198 non-null    int64
 5   stations               198 non-null    int64
 6   length_km              198 non-null    int64
 7   annual_ridership_mill  198 non-null    float64
 8   region                 198 non-null    str
dtypes: float64(1), int64(4), str(4)
memory usage: 14.1 KB

In [12]:
df.describe()

,year,year_last_expansion,stations,length_km,annual_ridership_mill
count,198.000000,198.000000,198.000000,198.000000,198.000000
mean,1987.858586,2014.565657,68.939394,1506.595960,263.254980
std,31.617161,13.167921,76.200753,4900.037419,482.654133
min,1890.000000,1896.000000,6.000000,12.000000,0.000000
25%,1976.000000,2014.000000,21.000000,175.000000,24.025000
50%,1995.500000,2019.000000,41.000000,392.000000,92.950000
75%,2012.750000,2021.000000,90.750000,1001.250000,247.925000
max,2022.000000,2022.000000,424.000000,49039.000000,2834.690000